### ISSUE TITLE
Author does not understand simple PHP, CSS, HTML and Javascript

### ISSUE THREAD

**Issue by antoniacobaeus** [Foxmaner/gokartBooking#7]
I have reviewed your code and it is **shit**. Please take one of Github's education courses to learn about the basics before you attempt something no one will use. 

As @AdamGSchmidt mentioned in another issue the CSS is just not up to the standards of today's society, I have provided some examples of excellent websites with good use of CSS. 

http://gatesnfences.com/
https://sms13.schoolsoft.se/nacka/jsp/Login.jsp
http://www.4chan.org/

**Comment by Foxmaner** [comment]
Woah! That´s interesting but I sure don´t care!
